import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";
import { fetchPurchaseRequisitions } from "@/api/fetchers";
import type { PurchaseRequisitionView } from "@/api/types";
import { StatusBadge, inferStatusKind } from "@/components/ui/StatusBadge";
import { truncateUuid } from "@/lib/utils";
import { PERSONAS } from "@/personas";

export function PurchaseRequisitions() {
  const persona = PERSONAS.tom;
  const { data, isLoading, error } = useQuery({
    queryKey: ["purchase-requisitions"],
    queryFn: fetchPurchaseRequisitions,
    refetchInterval: 5_000,
  });

  const list = data ?? [];
  const sorted = [...list].sort((a, b) => a.requisitionNumber.localeCompare(b.requisitionNumber));

  return (
    <div className="space-y-4">
      <div className="flex items-baseline gap-3">
        <h1 className="text-[28px] font-semibold tracking-tight">Purchase requisitions</h1>
        <span className="flex items-center gap-2 text-sm text-text-muted">
          <span className="h-1.5 w-1.5 rounded-full" style={{ background: persona.accentVar }} aria-hidden />
          {persona.name} · {persona.role}
        </span>
        <span className="ml-auto text-xs text-text-faint">
          {isLoading ? "loading…" : `${list.length} requisitions`}
        </span>
      </div>

      <p className="text-sm text-text-muted">
        Two creation paths: <span className="font-mono">manual</span> (REST entry from a buyer) and{" "}
        <span className="font-mono">work_order_shortage</span> (auto-generated by the manufacturing
        shortage detector). Manual PRs land at <span className="font-mono">draft</span>, shortage
        PRs auto-approve via the converted PO depending on{" "}
        <span className="font-mono">northwood.purchasing.shortagePoAutoApprove</span>.
      </p>

      {error && (
        <div
          className="rounded-md border px-4 py-3 text-sm"
          style={{
            borderColor: "var(--color-state-error)",
            background: "color-mix(in srgb, var(--color-state-error) 12%, transparent)",
          }}
        >
          <p className="font-medium" style={{ color: "var(--color-state-error)" }}>
            Couldn't reach purchasing-service on :8085
          </p>
          <p className="mt-1 text-text-muted">{String(error)}</p>
        </div>
      )}

      <div className="overflow-hidden rounded-lg border border-border-subtle bg-bg-elevated">
        <table className="w-full text-sm">
          <thead className="border-b border-border-subtle bg-bg-base/50 text-left text-[11px] uppercase tracking-wider text-text-muted">
            <tr>
              <th className="w-8"></th>
              <th className="px-3 py-2 font-semibold">PR #</th>
              <th className="px-3 py-2 font-semibold">Source</th>
              <th className="px-3 py-2 font-semibold">Source WO</th>
              <th className="px-3 py-2 font-semibold">Requested by</th>
              <th className="px-3 py-2 text-right font-semibold">Lines</th>
              <th className="px-3 py-2 font-semibold">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border-subtle">
            {sorted.map((pr) => <PrRow key={pr.id} pr={pr} />)}
          </tbody>
        </table>
        {!isLoading && list.length === 0 && !error && (
          <p className="px-4 py-6 text-center text-sm text-text-faint">
            No requisitions yet. Drive a make-to-order shortage scenario to see auto-generated PRs.
          </p>
        )}
      </div>
    </div>
  );
}

function PrRow({ pr }: { pr: PurchaseRequisitionView }) {
  const [open, setOpen] = useState(false);
  return (
    <>
      <tr className="hover:bg-bg-hover">
        <td className="px-2 py-2 align-top">
          <button
            type="button"
            onClick={() => setOpen((o) => !o)}
            className="text-text-muted hover:text-text-primary"
            aria-label={open ? "Collapse" : "Expand"}
          >
            {open ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
          </button>
        </td>
        <td className="px-3 py-2 font-mono">{pr.requisitionNumber}</td>
        <td className="px-3 py-2">
          <SourceBadge sourceType={pr.sourceType} />
        </td>
        <td className="px-3 py-2 font-mono text-xs text-text-faint">
          {pr.sourceWorkOrderId ? truncateUuid(pr.sourceWorkOrderId) : "—"}
        </td>
        <td className="px-3 py-2 text-text-muted">{pr.requestedBy}</td>
        <td className="px-3 py-2 text-right tabular-nums">{pr.lines.length}</td>
        <td className="px-3 py-2">
          <StatusBadge kind={inferStatusKind(pr.status)}>{pr.status}</StatusBadge>
        </td>
      </tr>
      {open && (
        <tr>
          <td colSpan={7} className="bg-bg-base/40 px-8 py-3">
            <table className="w-full text-xs">
              <thead className="border-b border-border-subtle text-left text-[10px] uppercase tracking-wider text-text-muted">
                <tr>
                  <th className="px-2 py-1.5 font-semibold">#</th>
                  <th className="px-2 py-1.5 font-semibold">Product</th>
                  <th className="px-2 py-1.5 text-right font-semibold">Qty</th>
                  <th className="px-2 py-1.5 font-semibold">Required by</th>
                  <th className="px-2 py-1.5 font-semibold">Suggested supplier</th>
                  <th className="px-2 py-1.5 font-semibold">Line status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border-subtle">
                {pr.lines.map((l) => (
                  <tr key={l.lineId}>
                    <td className="px-2 py-1 text-text-faint">{l.lineNumber}</td>
                    <td className="px-2 py-1">
                      <span className="font-mono text-text-faint">{l.productSku}</span>{" "}
                      <span>{l.productName}</span>
                    </td>
                    <td className="px-2 py-1 text-right tabular-nums">{l.requestedQuantity}</td>
                    <td className="px-2 py-1 text-text-muted">{l.requiredDate ?? "—"}</td>
                    <td className="px-2 py-1 text-text-muted">{l.suggestedSupplierName}</td>
                    <td className="px-2 py-1">
                      <StatusBadge kind={inferStatusKind(l.status)}>{l.status}</StatusBadge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="mt-2 text-[11px] text-text-faint">
              id: <span className="font-mono">{truncateUuid(pr.id)}</span>
              {pr.sourceProductId && <> · source product <span className="font-mono">{truncateUuid(pr.sourceProductId)}</span></>}
            </p>
          </td>
        </tr>
      )}
    </>
  );
}

function SourceBadge({ sourceType }: { sourceType: string }) {
  if (sourceType === "manual") {
    return <StatusBadge kind="pending">manual</StatusBadge>;
  }
  if (sourceType === "work_order_shortage") {
    return <StatusBadge kind="warn">shortage-driven</StatusBadge>;
  }
  return <StatusBadge>{sourceType}</StatusBadge>;
}
