# ===========================================================================
# Infra tier — docs/aws-demo-deployment.md §5.
# Postgres / Kafka / Keycloak, each on its own EC2 in the infra subnet.
# No SSH / no public IP — shell access is via SSM Session Manager.
#
# db/ files + the generated per-service-login SQL + per-box env files are
# staged in a PRIVATE, encrypted artifacts bucket; user-data pulls them. This
# keeps passwords out of user-data (which is readable via IMDS / the console).
# ===========================================================================

data "aws_ssm_parameter" "al2023" {
  count = var.ami_id == "" ? 1 : 0
  name  = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

data "aws_region" "current" {}

locals {
  ami_id = var.ami_id != "" ? var.ami_id : data.aws_ssm_parameter.al2023[0].value

  # ALTER ROLE ... LOGIN so each service authenticates as its own role.
  # Single quotes in passwords are doubled per SQL string-literal escaping.
  service_logins_sql = join("\n", [
    for svc, pw in var.service_db_passwords :
    "ALTER ROLE ${svc}_service WITH LOGIN PASSWORD '${replace(pw, "'", "''")}';"
  ])
}

# --------------------------------------------------------------------------
# Artifacts / staging bucket (private)
# --------------------------------------------------------------------------

resource "aws_s3_bucket" "artifacts" {
  bucket_prefix = "${var.name_prefix}-artifacts-"
  force_destroy = true # demo: let `terraform destroy` empty it
}

resource "aws_s3_bucket_public_access_block" "artifacts" {
  bucket                  = aws_s3_bucket.artifacts.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# ---- staged objects: db init scripts, realm, generated logins, env files ----

resource "aws_s3_object" "baseline_sql" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "db/01-northwood_erp.sql"
  source = "${var.repo_root}/db/northwood_erp.sql"
  etag   = filemd5("${var.repo_root}/db/northwood_erp.sql")
}

resource "aws_s3_object" "seed_sql" {
  count  = var.load_seed_data ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "db/02-northwood_erp_seed.sql"
  source = "${var.repo_root}/db/northwood_erp_seed.sql"
  etag   = filemd5("${var.repo_root}/db/northwood_erp_seed.sql")
}

resource "aws_s3_object" "service_logins_sql" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "db/03-service-logins.sql"
  content = "-- Generated by Terraform: grant LOGIN + password to each <svc>_service role.\n${local.service_logins_sql}\n"
}

resource "aws_s3_object" "realm" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "keycloak/northwood-realm.json"
  source = "${var.repo_root}/db/keycloak/northwood-realm.json"
  etag   = filemd5("${var.repo_root}/db/keycloak/northwood-realm.json")
}

resource "aws_s3_object" "postgres_env" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "env/postgres.env"
  content = "POSTGRES_PASSWORD=${var.postgres_superuser_password}\n"
}

resource "aws_s3_object" "keycloak_env" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "env/keycloak.env"
  content = "KC_BOOTSTRAP_ADMIN_PASSWORD=${var.keycloak_admin_password}\n"
}

# ---- observability config tree (staged only when enable_observability) -------
# Tempo + Loki configs are host-agnostic — staged verbatim from db/. The
# Grafana datasources + Prometheus config are AWS-tailored (see below).

resource "aws_s3_object" "obs_tempo" {
  count  = var.enable_observability ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "obs/tempo.yaml"
  source = "${var.repo_root}/db/tempo/tempo.yaml"
  etag   = filemd5("${var.repo_root}/db/tempo/tempo.yaml")
}

resource "aws_s3_object" "obs_loki" {
  count  = var.enable_observability ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "obs/loki-config.yaml"
  source = "${var.repo_root}/db/loki/loki-config.yaml"
  etag   = filemd5("${var.repo_root}/db/loki/loki-config.yaml")
}

# Prometheus on Fargate can't reach tasks by the compose `host.docker.internal`
# targets, and Fargate tasks have no stable IPs — so service scraping needs
# service discovery (ECS SD / Cloud Map, or an OTel/ADOT collector pushing OTLP
# metrics into the receiver enabled in user-data). That's a documented follow-up;
# traces + logs are the working push-based telemetry. This config self-scrapes
# and leaves the SD job as a commented stub so the path is obvious.
resource "aws_s3_object" "obs_prometheus" {
  count   = var.enable_observability ? 1 : 0
  bucket  = aws_s3_bucket.artifacts.id
  key     = "obs/prometheus.yml"
  content = <<-EOT
    # Northwood Prometheus — AWS demo (generated by Terraform).
    #
    # Service-metric scraping on Fargate needs service discovery; it is NOT wired
    # here. Either add an ECS SD job (`ecs_sd_configs` via the cloudwatch-agent /
    # an ECS SD exporter), or push OTLP metrics from the apps into this server's
    # OTLP receiver (started with --web.enable-otlp-receiver in user-data) at
    # http://<obs-private-dns>:9090/api/v1/otlp/v1/metrics. Until then the §1D
    # Grafana metric panels stay empty on AWS; traces + logs work out of the box.
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: northwood-demo-aws

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]

      # --- service scraping (enable once SD is wired) --------------------------
      # - job_name: northwood-services
      #   metrics_path: /actuator/prometheus
      #   ecs_sd_configs: [ ... ]   # or relabel from a Cloud Map / SD exporter
  EOT
}

resource "aws_s3_object" "obs_grafana_datasources" {
  count  = var.enable_observability ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "obs/grafana/datasources/datasources.yaml"
  content = templatefile("${path.module}/templates/grafana-datasources.yaml.tftpl", {
    postgres_host     = aws_instance.postgres.private_dns
    postgres_password = var.postgres_superuser_password
  })
}

resource "aws_s3_object" "obs_grafana_dashboards_provisioning" {
  count  = var.enable_observability ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "obs/grafana/dashboards-provisioning/dashboards.yaml"
  source = "${var.repo_root}/db/grafana/provisioning/dashboards/dashboards.yaml"
  etag   = filemd5("${var.repo_root}/db/grafana/provisioning/dashboards/dashboards.yaml")
}

resource "aws_s3_object" "obs_grafana_dashboard_json" {
  count  = var.enable_observability ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "obs/grafana/dashboards/northwood-overview.json"
  source = "${var.repo_root}/db/grafana/dashboards/northwood-overview.json"
  etag   = filemd5("${var.repo_root}/db/grafana/dashboards/northwood-overview.json")
}

# --------------------------------------------------------------------------
# IAM: instance role with SSM + read-only on the artifacts bucket
# --------------------------------------------------------------------------

data "aws_iam_policy_document" "assume_ec2" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "infra" {
  name               = "${var.name_prefix}-infra-ec2"
  assume_role_policy = data.aws_iam_policy_document.assume_ec2.json
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.infra.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

data "aws_iam_policy_document" "artifacts_read" {
  statement {
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.artifacts.arn}/*"]
  }
  statement {
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_bucket.artifacts.arn]
  }
}

resource "aws_iam_role_policy" "artifacts_read" {
  name   = "artifacts-read"
  role   = aws_iam_role.infra.id
  policy = data.aws_iam_policy_document.artifacts_read.json
}

resource "aws_iam_instance_profile" "infra" {
  name = "${var.name_prefix}-infra-ec2"
  role = aws_iam_role.infra.name
}

# --------------------------------------------------------------------------
# EC2 instances
# Root volume is sized to hold /data (gp3) — it persists across stop/start, so
# the demo's "stop instances to cut cost" path keeps DB + Kafka state.
# --------------------------------------------------------------------------

resource "aws_instance" "postgres" {
  ami                    = local.ami_id
  instance_type          = var.instance_types.postgres
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [var.security_group_ids.postgres]
  iam_instance_profile   = aws_iam_instance_profile.infra.name

  root_block_device {
    volume_type = "gp3"
    volume_size = var.data_volume_size_gb + 8
  }

  user_data = templatefile("${path.module}/templates/postgres.sh.tftpl", {
    region          = data.aws_region.current.name
    bucket          = aws_s3_bucket.artifacts.id
    image           = var.images.postgres
    env_key         = aws_s3_object.postgres_env.key
    init_key_prefix = "db/"
  })

  tags = { Name = "${var.name_prefix}-postgres" }
  depends_on = [
    aws_s3_object.baseline_sql,
    aws_s3_object.seed_sql, # no-op when load_seed_data = false (count 0)
    aws_s3_object.service_logins_sql,
    aws_s3_object.postgres_env,
  ]
}

resource "aws_instance" "kafka" {
  ami                    = local.ami_id
  instance_type          = var.instance_types.kafka
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [var.security_group_ids.kafka]
  iam_instance_profile   = aws_iam_instance_profile.infra.name

  root_block_device {
    volume_type = "gp3"
    volume_size = var.data_volume_size_gb + 8
  }

  user_data = templatefile("${path.module}/templates/kafka.sh.tftpl", {
    image      = var.images.kafka
    cluster_id = var.kafka_cluster_id
  })

  tags = { Name = "${var.name_prefix}-kafka" }
}

resource "aws_instance" "keycloak" {
  ami                    = local.ami_id
  instance_type          = var.instance_types.keycloak
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [var.security_group_ids.keycloak]
  iam_instance_profile   = aws_iam_instance_profile.infra.name

  root_block_device {
    volume_type = "gp3"
    volume_size = 12
  }

  user_data = templatefile("${path.module}/templates/keycloak.sh.tftpl", {
    region    = data.aws_region.current.name
    bucket    = aws_s3_bucket.artifacts.id
    image     = var.images.keycloak
    env_key   = aws_s3_object.keycloak_env.key
    realm_key = aws_s3_object.realm.key
    hostname  = var.keycloak_hostname
  })

  tags       = { Name = "${var.name_prefix}-keycloak" }
  depends_on = [aws_s3_object.realm, aws_s3_object.keycloak_env]
}

# --------------------------------------------------------------------------
# Observability box — LGTM stack (Loki/Grafana/Tempo + Prometheus).
# Receives OTLP traces (4317/4318) and Loki log push (3100) from the app +
# web tiers; Grafana (3000) is reached via SSM port-forward. Gated on
# enable_observability so the box (and its cost) can be turned off.
# --------------------------------------------------------------------------

resource "aws_instance" "observability" {
  count                  = var.enable_observability ? 1 : 0
  ami                    = local.ami_id
  instance_type          = var.observability_instance_type
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [var.security_group_ids.obs]
  iam_instance_profile   = aws_iam_instance_profile.infra.name

  root_block_device {
    volume_type = "gp3"
    volume_size = var.data_volume_size_gb + 8
  }

  user_data = templatefile("${path.module}/templates/observability.sh.tftpl", {
    region           = data.aws_region.current.name
    bucket           = aws_s3_bucket.artifacts.id
    key_prefix       = "obs/"
    image_tempo      = var.observability_images.tempo
    image_loki       = var.observability_images.loki
    image_prometheus = var.observability_images.prometheus
    image_grafana    = var.observability_images.grafana
  })

  tags = { Name = "${var.name_prefix}-observability" }
  depends_on = [
    aws_s3_object.obs_tempo,
    aws_s3_object.obs_loki,
    aws_s3_object.obs_prometheus,
    aws_s3_object.obs_grafana_datasources,
    aws_s3_object.obs_grafana_dashboards_provisioning,
    aws_s3_object.obs_grafana_dashboard_json,
  ]
}
