# ===========================================================================
# Compute tier — docs/aws-deployment.html. Three EC2 instances, each running
# the relevant containers via `docker run` (the demo's docker-compose-on-a-VM
# model), no ECS/Fargate:
#
#   web  (public subnet, public IP)  : erp-web-ui-bff + Keycloak
#   app  (private subnet)            : the 7 services
#   data (private subnet)            : Postgres + Kafka + (optional) observability
#
# Cross-tier URLs are wired from the pinned static private IPs (var.private_ips)
# so user-data is computed at plan time with no instance-to-instance dependency
# cycle. The private boxes egress through the network module's NAT instance:
# the 8 app images come from ECR (pushed by the build script); the third-party
# images (Postgres/Kafka/Keycloak/LGTM) are pulled straight from Docker Hub /
# quay.io.
#
# No SSH / no public-key auth — shell is SSM Session Manager (the agent reaches
# AWS through the NAT instance).
# ===========================================================================

data "aws_ssm_parameter" "al2023" {
  count = var.ami_id == "" ? 1 : 0
  name  = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

data "aws_region" "current" {}

locals {
  ami_id = var.ami_id != "" ? var.ami_id : data.aws_ssm_parameter.al2023[0].value

  data_ip = var.private_ips.infra
  app_ip  = var.private_ips.app
  web_ip  = var.private_ips.web

  # Keycloak's public issuer (browser OIDC). Defaults to the web box's stable
  # Elastic IP so browser login works out of the box; an explicit
  # var.keycloak_hostname (e.g. a DNS name) still overrides it.
  kc_host   = var.keycloak_hostname != "" ? var.keycloak_hostname : aws_eip.web.public_ip
  kc_issuer = "http://${local.kc_host}:8080/realms/northwood"

  # The front-door "Enter the ERP" / Demo-Guide links target the public BFF.
  # Reuses kc_host (the public hostname set via var.keycloak_hostname) so it's
  # browser-reachable once OIDC is wired — same chicken-and-egg as kc_issuer:
  # until keycloak_hostname is set it points at the web private IP.
  erp_url = "http://${local.kc_host}:${var.bff_port}"

  kafka_boot    = "${local.data_ip}:9092"
  otlp_endpoint = var.enable_observability ? "http://${local.data_ip}:4317" : ""
  loki_url      = var.enable_observability ? "http://${local.data_ip}:3100/loki/api/v1/push" : ""

  # ALTER ROLE … LOGIN so each service authenticates as its own role.
  service_logins_sql = join("\n", [
    for svc, pw in var.service_db_passwords :
    "ALTER ROLE ${svc}_service WITH LOGIN PASSWORD '${replace(pw, "'", "''")}';"
  ])

  # `<SVC>_DB_PASSWORD=…` lines staged as a private env file for the app box.
  service_db_env = join("\n", [
    for svc, pw in var.service_db_passwords : "${upper(svc)}_DB_PASSWORD=${pw}"
  ])
}

# --------------------------------------------------------------------------
# Artifacts / staging bucket (private, encrypted) — db init, realm, env files.
# --------------------------------------------------------------------------

resource "aws_s3_bucket" "artifacts" {
  bucket_prefix = "${var.name_prefix}-artifacts-"
  force_destroy = true
}

resource "aws_s3_bucket_public_access_block" "artifacts" {
  bucket                  = aws_s3_bucket.artifacts.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  rule {
    apply_server_side_encryption_by_default { sse_algorithm = "AES256" }
  }
}

resource "aws_s3_object" "baseline_sql" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "db/01-northwood_erp.sql"
  source = "${var.repo_root}/config/postgresql/northwood_erp.sql"
  etag   = filemd5("${var.repo_root}/config/postgresql/northwood_erp.sql")
}

resource "aws_s3_object" "seed_sql" {
  count  = var.load_seed_data ? 1 : 0
  bucket = aws_s3_bucket.artifacts.id
  key    = "db/02-northwood_erp_seed.sql"
  source = "${var.repo_root}/config/postgresql/northwood_erp_seed.sql"
  etag   = filemd5("${var.repo_root}/config/postgresql/northwood_erp_seed.sql")
}

resource "aws_s3_object" "service_logins_sql" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "db/03-service-logins.sql"
  content = "-- Generated by Terraform: grant LOGIN + password to each <svc>_service role.\n${local.service_logins_sql}\n"
}

resource "aws_s3_object" "realm" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "keycloak/northwood-realm.json"
  source = "${var.repo_root}/config/keycloak/northwood-realm.json"
  etag   = filemd5("${var.repo_root}/config/keycloak/northwood-realm.json")
}

# Guest front-door page template. The web box renders ${ERP_URL} at boot
# (host-side sed) before serving it via a plain nginx container — same output
# as the docker-compose envsubst path, different runtime.
resource "aws_s3_object" "welcome_template" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "welcome/index.html.template"
  source = "${var.repo_root}/config/welcome.html.template"
  etag   = filemd5("${var.repo_root}/config/welcome.html.template")
}

resource "aws_s3_object" "postgres_env" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "env/postgres.env"
  content = "POSTGRES_PASSWORD=${var.postgres_superuser_password}\n"
}

resource "aws_s3_object" "keycloak_env" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "env/keycloak.env"
  content = "KC_BOOTSTRAP_ADMIN_PASSWORD=${var.keycloak_admin_password}\n"
}

resource "aws_s3_object" "services_env" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "env/services.env"
  content = "${local.service_db_env}\n"
}

resource "aws_s3_object" "bff_env" {
  bucket  = aws_s3_bucket.artifacts.id
  key     = "env/bff.env"
  content = "KEYCLOAK_BFF_CLIENT_SECRET=${var.bff_client_secret}\n"
}

# ---- observability config tree (only when enabled) -------------------------
resource "aws_s3_object" "obs_config" {
  for_each = var.enable_observability ? {
    "obs/tempo.yaml"                                      = "${var.repo_root}/config/tempo/tempo.yaml"
    "obs/loki-config.yaml"                                = "${var.repo_root}/config/loki/loki-config.yaml"
    "obs/prometheus.yml"                                  = "${var.repo_root}/config/prometheus/prometheus.yml"
    "obs/grafana/datasources/datasources.yaml"            = "${var.repo_root}/config/grafana/provisioning/datasources/datasources.yaml"
    "obs/grafana/dashboards-provisioning/dashboards.yaml" = "${var.repo_root}/config/grafana/provisioning/dashboards/dashboards.yaml"
    "obs/grafana/dashboards/northwood-overview.json"      = "${var.repo_root}/config/grafana/dashboards/northwood-overview.json"
  } : {}
  bucket = aws_s3_bucket.artifacts.id
  key    = each.key
  source = each.value
  etag   = filemd5(each.value)
}

# --------------------------------------------------------------------------
# IAM — instance role: SSM + read the artifacts bucket + pull from ECR.
# --------------------------------------------------------------------------

data "aws_iam_policy_document" "assume_ec2" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "compute" {
  name               = "${var.name_prefix}-compute-ec2"
  assume_role_policy = data.aws_iam_policy_document.assume_ec2.json
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.compute.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

data "aws_iam_policy_document" "instance" {
  statement {
    sid       = "ArtifactsRead"
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.artifacts.arn}/*"]
  }
  statement {
    sid       = "ArtifactsList"
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_bucket.artifacts.arn]
  }
  statement {
    sid       = "EcrAuth"
    actions   = ["ecr:GetAuthorizationToken"]
    resources = ["*"]
  }
  statement {
    sid       = "EcrPull"
    actions   = ["ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer", "ecr:BatchCheckLayerAvailability"]
    resources = var.ecr_repository_arns
  }
}

resource "aws_iam_role_policy" "instance" {
  name   = "compute-instance"
  role   = aws_iam_role.compute.id
  policy = data.aws_iam_policy_document.instance.json
}

resource "aws_iam_instance_profile" "compute" {
  name = "${var.name_prefix}-compute-ec2"
  role = aws_iam_role.compute.name
}

# --------------------------------------------------------------------------
# EC2 instances — data first (no deps), then app, then web (linear refs).
# --------------------------------------------------------------------------

resource "aws_instance" "data" {
  ami                    = local.ami_id
  instance_type          = var.instance_types.data
  subnet_id              = var.subnet_ids.infra
  private_ip             = local.data_ip
  vpc_security_group_ids = [var.security_group_ids.infra]
  iam_instance_profile   = aws_iam_instance_profile.compute.name

  root_block_device {
    volume_type = "gp3"
    volume_size = var.data_volume_size_gb + 8
  }

  user_data = templatefile("${path.module}/templates/data.sh.tftpl", {
    region               = data.aws_region.current.name
    bucket               = aws_s3_bucket.artifacts.id
    registry             = var.ecr_registry
    postgres_image       = var.images.postgres
    kafka_image          = var.images.kafka
    kafka_cluster_id     = var.kafka_cluster_id
    advertise_ip         = local.data_ip
    enable_observability = var.enable_observability
    obs_images           = var.observability_images
  })

  tags       = { Name = "${var.name_prefix}-data" }
  depends_on = [aws_s3_object.baseline_sql, aws_s3_object.seed_sql, aws_s3_object.service_logins_sql, aws_s3_object.postgres_env, aws_s3_object.obs_config]
}

resource "aws_instance" "app" {
  ami                    = local.ami_id
  instance_type          = var.instance_types.app
  subnet_id              = var.subnet_ids.app
  private_ip             = local.app_ip
  vpc_security_group_ids = [var.security_group_ids.app]
  iam_instance_profile   = aws_iam_instance_profile.compute.name

  root_block_device {
    volume_type = "gp3"
    volume_size = 20
  }

  user_data = templatefile("${path.module}/templates/app.sh.tftpl", {
    region        = data.aws_region.current.name
    bucket        = aws_s3_bucket.artifacts.id
    registry      = var.ecr_registry
    image_prefix  = var.image_prefix
    image_tag     = var.image_tag
    services      = var.services
    data_ip       = local.data_ip
    kafka_boot    = local.kafka_boot
    kc_issuer     = local.kc_issuer
    otlp_endpoint = local.otlp_endpoint
    loki_url      = local.loki_url
  })

  tags       = { Name = "${var.name_prefix}-app" }
  depends_on = [aws_s3_object.services_env, aws_instance.data]
}

resource "aws_instance" "web" {
  ami                    = local.ami_id
  instance_type          = var.instance_types.web
  subnet_id              = var.subnet_ids.public
  private_ip             = local.web_ip
  vpc_security_group_ids = [var.security_group_ids.web]
  iam_instance_profile   = aws_iam_instance_profile.compute.name

  root_block_device {
    volume_type = "gp3"
    volume_size = 16
  }

  user_data = templatefile("${path.module}/templates/web.sh.tftpl", {
    region         = data.aws_region.current.name
    bucket         = aws_s3_bucket.artifacts.id
    registry       = var.ecr_registry
    image_prefix   = var.image_prefix
    image_tag      = var.image_tag
    keycloak_image = var.images.keycloak
    bff_name       = var.bff_name
    bff_port       = var.bff_port
    keycloak_host  = local.kc_host
    kc_issuer      = local.kc_issuer
    kafka_boot     = local.kafka_boot
    app_ip         = local.app_ip
    services       = var.services
    otlp_endpoint  = local.otlp_endpoint
    loki_url       = local.loki_url
    welcome_image  = var.welcome_image
    welcome_port   = var.welcome_port
    erp_url        = local.erp_url
  })

  tags       = { Name = "${var.name_prefix}-web" }
  depends_on = [aws_s3_object.realm, aws_s3_object.keycloak_env, aws_s3_object.bff_env, aws_s3_object.welcome_template, aws_instance.app]
}

# Stable public IP for the web box so the Keycloak issuer + front-door URLs
# survive instance replacement and stop/start. Allocation is kept separate from
# the association so web/app user_data can embed aws_eip.web.public_ip without a
# dependency cycle (the allocation does not reference the instance).
resource "aws_eip" "web" {
  domain = "vpc"
  tags   = { Name = "${var.name_prefix}-web" }
}

resource "aws_eip_association" "web" {
  allocation_id = aws_eip.web.id
  instance_id   = aws_instance.web.id
}
